"""随便学习

Revision ID: 762d84261a7a
Revises: 
Create Date: 2020-05-14 07:12:31.565148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762d84261a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('new', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_news')
    op.drop_table('ab_cat')
    # ### end Alembic commands ###
