"""add content

Revision ID: d4a084fdebf5
Revises: 762d84261a7a
Create Date: 2020-05-14 07:13:14.125049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a084fdebf5'
down_revision = '762d84261a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_cat', sa.Column('content', sa.String(length=21), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ab_cat', 'content')
    # ### end Alembic commands ###
